// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sisgfioufscldwlhtpsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpc2dmaW91ZnNjbGR3bGh0cHNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDc3NzMsImV4cCI6MjA2MzQyMzc3M30.Pgob6ki7pXPqVfuwCE_pBF7RAIroWD5LDGgJeMSrnWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);